### ISSUE TITLE
launch script typo? Omission?

### ISSUE THREAD

**Issue by jmidwint** [scottontech/posts#1]
Hi: Might be a small typo/omission on your examples of working launch scripts?  Take a look at the file name format value _value="frame%05.jpg" , which I think you meant to have the "d" type value so it would be 
value="frame%05d.jpg". The web page description where you provide the original descriptions of launch scripts seems to be ok.

Without having the correct type "d" , one would see this error being output:
..snip
setting /run_id to 0392b03c-a37e-11e6-bc67-080027102b84
process[rosout-1]: started with pid [30905]
started core service [/rosout]
process[rosbag-2]: started with pid [30908]
process[extract-3]: started with pid [30917]
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::io::bad_format_string> >'
  what():  boost::bad_format_string: format-string is ill-formed
[extract-3] process has died [pid 30917, exit code -6, cmd /opt/ros/jade/lib/image_view/extract_images image:=/left_camera/image_color __name:=extract __log:=/home/jennym/.ros/log/0392b03c-a37e-11e6-bc67-080027102b84/extract-3.log].
log file: /home/jennym/.ros/log/0392b03c-a37e-11e6-bc67-080027102b84/extract-3*.log

**Comment by scottontech** [comment]
You are absolutely correct.  I have fixed the typo in the three launch scripts.  Thank you!
